### ISSUE TITLE
Why not a minor mode?

### ISSUE THREAD

**Issue by sp1ff** [rougier/mu4e-dashboard#12]
This is more a question than an issue, but I'm wondering why you chose the approach of updating a single buffer (`mu4e-dashboard-buffer`) rather than a minor mode? I, for one, would like to have multiple dashboards active at any one time (say, one summary with just a few counts & one "live" dashboard like your "side" example).

**Comment by rougier** [comment]
Now that you ask the question, I realized I've no real answer and a minor mode might be actually easier to implement. I think I concentrated on having the async update and went to what seemed to be the easiest solution at that time.

**Comment by sp1ff** [comment]
Heh, well it occurred to me because someone [asked](https://github.com/melpa/melpa/pull/7190#issuecomment-723503603) me the same question when I was submitting a package of my own to MELPA ;)
Would you be open to a PR re-structuring the current logic as a minor mode?

**Comment by rougier** [comment]
@sp1ff Yes, I think it would simplify things. Also, you can have a look at [elfeed-dashboar](https://github.com/Manoj321/elfeed-dashboard) by @Manoj321. I think he took inspiration from mu4e dashboard for creating the elfeed dashboard. If we can have the same architecture for both of them, that could help. On the long term, maybe we can simply have an org-dahsboard that can be adapted to all dashboard, including u4e and elfeed.

**Comment by Manoj321** [comment]
Soon after elfeed-dashboard. I started to think in the direction of generalizing this as well and started orgdash: https://github.com/manojm321/orgdash (there isn't much to show yet, I only have a locally working copy)

Basically the idea is to leverage org source code blocks and use their results in the links. Similar to how [grafana](https://grafana.com/grafana/) works. I'll post more updates soon.

**Comment by sp1ff** [comment]
@Manoj321 looking forward to see what you propose.

In the meantime, I've opened [PR 16](https://github.com/rougier/mu4e-dashboard/pull/16) to address this issue.

**Comment by rougier** [comment]
Nice. Tried to merge but it conflicts with your other PR.

**Comment by sp1ff** [comment]
Huh.... OK, I *think* I've fixed it.

**Comment by sp1ff** [comment]
Closing this issue since you merged PR #16
