### ISSUE TITLE
Is the reference about mu4e-dashboard-activate current?

### ISSUE THREAD

**Issue by nickanderson** [rougier/mu4e-dashboard#20]
dashboard.org and side-dashboard.org mention mu4e-dashboard-activate and mu4e-dashboard-deactivate.
https://github.com/rougier/mu4e-dashboard/search?q=mu4e-dashboard-activate

I don't find any other references to these functions. Perhaps this is stale and should be removed?

**Comment by rougier** [comment]
Thanks, you're right. This dates from the early version when it was not a minor mode. Could you make a PR?
