### ISSUE TITLE
A version for notmuch

### ISSUE THREAD

**Issue by agenbite** [rougier/mu4e-dashboard#38]
Just for fun, I've replicated this package for notmuch. The result is [here](https://git.sr.ht/~inwit/org-notmuch-hello).

The main advantage that I see with respect to the standard notmuch-hello dashboard is that one can easily show unread/total counts for each search. It's not much, indeed.

**Comment by rougier** [comment]
Oh nice! I'll add a link to your repo in the README (or do you want to make a PR?)

**Comment by agenbite** [comment]
I thought about the PR, but since mu4e is in the very name of your project I thought it would make more sense to start a different project under a different name. On the other hand, my version replicates most of the code from yours and I don't think I'll be able to maintain it much further (not even sure I'll use it myself), so maybe it'd be a good idea to merge both. What do you think?

**Comment by rougier** [comment]
The PR would be only for the README to give a pointer to your repo (such that people will know the code exists). As for merging, my secret hope is someone will make a PR based on your code :)

**Comment by agenbite** [comment]
Done in #41 :)

**Comment by rougier** [comment]
Thanks! Merged.
