### ISSUE TITLE
Error if I read mail from mu4e-dashboard without first running mu4e

### ISSUE THREAD

**Issue by rhstanton** [rougier/mu4e-dashboard#52]
If I run mu4e-dashboard without first running mu4e, the dashboard page opens fine. But if I click to run one of the searches, I get an error like:
```
Debugger entered--Lisp error: (void-function nil)
  nil(500)
  mu4e--server-filter(#<process  *mu4e-server*> "\376b\377(:erase t)\n\37620aa7\377(:headers ((:path \"/Users/sta...")
```
All works fine as long as I've run mu4e first.

**Comment by rougier** [comment]
You should use something like

```emacs-lisp
(with-eval-after-load 'mu4e     (require 'mu4e-dashboard))
```

in your emacs.d config.
