### ISSUE TITLE
Link type will clash with exiting org-mu4e package

### ISSUE THREAD

**Issue by stsquad** [rougier/mu4e-dashboard#7]
https://github.com/rougier/mu4e-dashboard/blob/82278cc1525e4a69d9cd680c643b95b79baf65c8/mu4e-dashboard.el#L37

**Comment by rougier** [comment]
I did not think about that. Looking at [org-mu4e.el](https://github.com/djcb/mu/blob/master/mu4e/org-mu4e.el), I do not find the definition of mu4e links. Is that the one you're referring to?

**Comment by stsquad** [comment]
Confusingly there are two related files in the source tree. You want: https://github.com/djcb/mu/blob/master/mu4e/mu4e-org.el

**Comment by rougier** [comment]
Ok, so we need to  change :(

**Comment by sp1ff** [comment]
I think we can close this, now.
